Repository SWPC-IPE/WAM-IPE, pull requests merged in 2018-04, with the labels that each got.

#153 Joe issue150
  IPELIB/src/Makefile
  IPELIB/src/driver/driver_ipe.f90
  IPELIB/src/eldyn/module_sub_eldyn.f
  IPELIB/src/neutral/Makefile
  IPELIB/src/neutral/SMS_Module_Lookup.txt
  IPELIB/src/neutral/dat
  IPELIB/src/neutral/dwm07b104i.dat
  IPELIB/src/neutral/gd2qd.dat
  IPELIB/src/neutral/hwm123114.bin
  IPELIB/src/neutral/hwm14.f90
  IPELIB/src/neutral/hwm93.f90
  IPELIB/src/neutral/module_neutral.f90
  IPELIB/src/neutral/nrlmsise00_sub.f
  IPELIB/src/neutral/thermosphere_1d_v2.f90
  scripts/compsets/config/ipe.config
  scripts/compsets/march2013_regression.config
Labels: improvement

#158 Vector regridding
  IPELIB/src/eldyn/module_sunloc.f
  NEMS/src/conf/configure.nems.NUOPC
  NEMS/src/makefile
  NEMS/src/module_MEDIATOR_SWPC.F90
  NEMS/src/module_MEDIATOR_SWPC_methods.F90
  NEMS/src/module_MEDIATOR_SpaceWeather.F90
  modulefiles/theia/wam-ipe
Labels: improvement, new feature

#154 Fixed input parameters
  .gitignore
  scripts/compsets/config/ipe.config
  scripts/compsets/exglobal/exglobal_fcst_nems.sh
  scripts/compsets/submit.sh
  scripts/compsets/user.config
  scripts/interpolate_input_parameters/interpolate_input_parameters.py
  scripts/interpolate_input_parameters/parse.py
  scripts/interpolate_input_parameters/sw_from_f107_kp.py
  scripts/parse_f107_xml
  scripts/parse_f107_xml/parse.py
Labels: new feature
